// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyBXFdBZc4OmUyOgyaIlWDnRO4KBYNnO8zQ',
    appId: '1:1077018375331:web:aaa9e83c69a92440973b16',
    messagingSenderId: '1077018375331',
    projectId: 'fashion-app-929b2',
    authDomain: 'fashion-app-929b2.firebaseapp.com',
    storageBucket: 'fashion-app-929b2.firebasestorage.app',
    measurementId: 'G-VF870VRWJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxknRqFr_ImFVUUwEVlsIOqSzQtOO-M_0',
    appId: '1:1077018375331:android:d4d02ec70ad8e12f973b16',
    messagingSenderId: '1077018375331',
    projectId: 'fashion-app-929b2',
    storageBucket: 'fashion-app-929b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGRSFWOUntBccA7QJEgE5NOkqptwv73H4',
    appId: '1:1077018375331:ios:5d6bbe9d46c9a4ab973b16',
    messagingSenderId: '1077018375331',
    projectId: 'fashion-app-929b2',
    storageBucket: 'fashion-app-929b2.firebasestorage.app',
    iosBundleId: 'com.example.secondFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGRSFWOUntBccA7QJEgE5NOkqptwv73H4',
    appId: '1:1077018375331:ios:5d6bbe9d46c9a4ab973b16',
    messagingSenderId: '1077018375331',
    projectId: 'fashion-app-929b2',
    storageBucket: 'fashion-app-929b2.firebasestorage.app',
    iosBundleId: 'com.example.secondFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXFdBZc4OmUyOgyaIlWDnRO4KBYNnO8zQ',
    appId: '1:1077018375331:web:731f5a7dd33aeb36973b16',
    messagingSenderId: '1077018375331',
    projectId: 'fashion-app-929b2',
    authDomain: 'fashion-app-929b2.firebaseapp.com',
    storageBucket: 'fashion-app-929b2.firebasestorage.app',
    measurementId: 'G-36R7WE4LD9',
  );

}
=======
    apiKey: 'AIzaSyBw5ZUMfNbPwa5PKz9ygdzfWz0SZRYOVtE',
    appId: '1:741986168021:web:d4a40142cf6a602bdfc65c',
    messagingSenderId: '741986168021',
    projectId: 'apiproject-d4371',
    authDomain: 'apiproject-d4371.firebaseapp.com',
    storageBucket: 'apiproject-d4371.firebasestorage.app',
    measurementId: 'G-N8RBL67GYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdAg5ZvehIi56Yz9nwo3WNa7o1dqqNdF8',
    appId: '1:741986168021:android:31ab7c4febb49ef8dfc65c',
    messagingSenderId: '741986168021',
    projectId: 'apiproject-d4371',
    storageBucket: 'apiproject-d4371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-DRsya2oNAgWvNsstOCKzV0nTVNrEGI',
    appId: '1:741986168021:ios:3bfc6fdb26ce64c3dfc65c',
    messagingSenderId: '741986168021',
    projectId: 'apiproject-d4371',
    storageBucket: 'apiproject-d4371.firebasestorage.app',
    iosBundleId: 'com.example.apiProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-DRsya2oNAgWvNsstOCKzV0nTVNrEGI',
    appId: '1:741986168021:ios:3bfc6fdb26ce64c3dfc65c',
    messagingSenderId: '741986168021',
    projectId: 'apiproject-d4371',
    storageBucket: 'apiproject-d4371.firebasestorage.app',
    iosBundleId: 'com.example.apiProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw5ZUMfNbPwa5PKz9ygdzfWz0SZRYOVtE',
    appId: '1:741986168021:web:970e2042ca51a49cdfc65c',
    messagingSenderId: '741986168021',
    projectId: 'apiproject-d4371',
    authDomain: 'apiproject-d4371.firebaseapp.com',
    storageBucket: 'apiproject-d4371.firebasestorage.app',
    measurementId: 'G-0RTV95XMC8',
  );
}
>>>>>>> 8b54285 (api's practice)
